### ISSUE TITLE
Ethereum test shiftCombinations failed with panic

### ISSUE THREAD

**Issue by wsodsong** [Fantom-foundation/Carmen#846]
Carmen panics when processing shiftCombinations.

Test name: [GeneralStateTests/stShift/shiftCombinations.json](https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stShift/shiftCombinations.json)

```
build/aida-vm-sdb ethereum-test --validate-state-hash --continue-on-failure --db-impl carmen --db-variant go-file --carmen-schema 5 --shadow-db --db-shadow-impl geth --vm-impl geth --memory-breakdown --cpu-profile 21.cpuprofile --memory-profile 21.memprofile ../ethtests/GeneralStateTests/stShift/shiftCombinations.json
2024/05/06 03:24:29 WARNING: ChainID (--chainid) was not set; looking for it in AidaDb
2024/05/06 03:24:29 WARNING: ChainID was neither specified with flag (--chainid) nor was found in AidaDb (); setting default value for mainnet
2024/05/06 03:24:29 WARNING: Temporary directory  is not found. Use the system default /tmp.
2024/05/06 03:24:29 NOTICE: Run config:
2024/05/06 03:24:29 INFO: Block range: 0 to 0
2024/05/06 03:24:29 INFO: Chain id: 250 (record & run-vm only)
2024/05/06 03:24:29 INFO: SyncPeriod length: 300
2024/05/06 03:24:29 NOTICE: Used VM implementation: geth
2024/05/06 03:24:29 INFO: Aida DB directory:
2024/05/06 03:24:29 INFO: validate tx state: true
2024/05/06 03:24:29 WARNING: DB shadowing enabled, reducing Tx throughput and increasing memory and storage usage
2024/05/06 03:24:29 NOTICE: Run stShift/shiftCombinations.json - (London)
panic: unable to store extension node with dirty hash

goroutine 147 [running]:
github.com/Fantom-foundation/Carmen/go/database/mpt.ExtensionNodeEncoderWithChildHash.Store({}, {0xc0002fc050?, 0x0?, 0xa?}, 0x0?)
        /home/wawa/dev/aida5/carmen/go/database/mpt/nodes.go:2160 +0x20f
github.com/Fantom-foundation/Carmen/go/backend/stock/file.(*fileStock[...]).Set(0x10c1a80, 0x1, {{{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...})
        /home/wawa/dev/aida5/carmen/go/backend/stock/file/file.go:276 +0x13c
github.com/Fantom-foundation/Carmen/go/backend/stock/synced.(*syncedStock[...]).Set(0x1000000625702?, 0xf388b7?, {{{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...})
        /home/wawa/dev/aida5/carmen/go/backend/stock/synced/synced.go:51 +0xf9
github.com/Fantom-foundation/Carmen/go/database/mpt.(*Forest).flushNode(0x0?, 0x429844?, {0x10ba950?, 0xc00042a510?})
        /home/wawa/dev/aida5/carmen/go/database/mpt/forest.go:877 +0x298
github.com/Fantom-foundation/Carmen/go/database/mpt.writeBufferSink.Write({0xe05080?}, 0xc0003fdf80?, {{0xc017276240}})
        /home/wawa/dev/aida5/carmen/go/database/mpt/forest.go:1020 +0x25
github.com/Fantom-foundation/Carmen/go/database/mpt.(*writeBuffer).emptyBuffer(0xc000425300)
        /home/wawa/dev/aida5/carmen/go/database/mpt/write_buffer.go:210 +0x354
github.com/Fantom-foundation/Carmen/go/database/mpt.makeWriteBuffer.func1()
        /home/wawa/dev/aida5/carmen/go/database/mpt/write_buffer.go:106 +0xe5
created by github.com/Fantom-foundation/Carmen/go/database/mpt.makeWriteBuffer in goroutine 63
        /home/wawa/dev/aida5/carmen/go/database/mpt/write_buffer.go:100 +0x1ab
```

Expected result using geth
```
build/aida-vm-sdb ethereum-test --validate-state-hash --continue-on-failure --db-impl geth --vm-impl geth --memory-breakdown --cpu-profile 21.cpuprofile --memory-profile 21.memprofi
le ../ethtests/GeneralStateTests/stShift/shiftCombinations.json
2024/05/06 04:03:51 WARNING: ChainID (--chainid) was not set; looking for it in AidaDb
INFO [05-06|04:03:51.250] Allocated cache and file handles         database= cache=1024.00MiB handles=100 readonly=true
2024/05/06 04:03:51 WARNING: ChainID was neither specified with flag (--chainid) nor was found in AidaDb (); setting default value for mainnet
2024/05/06 04:03:51 WARNING: Temporary directory  is not found. Use the system default /tmp.
2024/05/06 04:03:51 NOTICE: Run config:
2024/05/06 04:03:51 INFO: Block range: 0 to 0
2024/05/06 04:03:51 INFO: Chain id: 250 (record & run-vm only)
2024/05/06 04:03:51 INFO: SyncPeriod length: 300
2024/05/06 04:03:51 NOTICE: Used VM implementation: geth
2024/05/06 04:03:51 INFO: Aida DB directory:
2024/05/06 04:03:51 INFO: validate tx state: true
INFO [05-06|04:03:51.251] Allocated cache and file handles         database=/tmp/state_db_tmp_552958570 cache=512.00MiB  handles=128
2024/05/06 04:03:51 NOTICE: Run stShift/shiftCombinations.json - (London)
INFO [05-06|04:03:51.276] Persisted trie from memory database      nodes=2623 size=267.97KiB time=5.485892ms gcnodes=4 gcsize=476.00B gctime="4.268µs" livenodes=1 livesize=-82.00B
INFO [05-06|04:03:51.277] Allocated cache and file handles         database=/tmp/state_db_tmp_450286568 cache=512.00MiB  handles=128
2024/05/06 04:03:51 NOTICE: Run stShift/shiftCombinations.json - (Berlin)
INFO [05-06|04:03:51.303] Persisted trie from memory database      nodes=2623 size=267.97KiB time=6.936049ms gcnodes=4 gcsize=476.00B gctime="3.426µs" livenodes=1 livesize=-82.00B
INFO [05-06|04:03:51.304] Allocated cache and file handles         database=/tmp/state_db_tmp_3626607331 cache=512.00MiB  handles=128
2024/05/06 04:03:51 NOTICE: Run stShift/shiftCombinations.json - (Istanbul)
INFO [05-06|04:03:51.326] Persisted trie from memory database      nodes=2623 size=267.97KiB time=6.872311ms gcnodes=0 gcsize=0.00B   gctime=0s        livenodes=5 livesize=394.00B
2024/05/06 04:03:51 NOTICE: Total 3 tests processed.
2024/05/06 04:03:51 NOTICE: Total elapsed time: 0s; last block 37534834; total transaction rate ~39.57 Tx/s, ~1849.15 MGas/s
```

**Comment by HerbertJordan** [comment]
It looks to me like the cache used for storing nodes for the LiveDB is not large enough for this test case. I will try to verify this.
