### ISSUE TITLE
Race detector failed due to nil-pointer access

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Carmen#964]
An issue was detected by the Race-Detector job's [91](https://scala.fantom.network/job/Carmen/job/Race-Detection/91/console) run:
```
08:44:28  Failed to fetch root: failed to call Getpanic: runtime error: invalid memory address or nil pointer dereference
08:44:28  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8882ca]
08:44:28  
08:44:28  goroutine 6929 [running]:
08:44:28  github.com/Fantom-foundation/Carmen/go/database/mpt/shared.(*Shared[...]).TryGetViewHandle(0xc2f6a1bbbf)
08:44:28  	/tmp/workspace/Carmen/Race-Detection/carmen/go/database/mpt/shared/shared.go:92 +0x2a
08:44:28  github.com/Fantom-foundation/Carmen/go/database/mpt.tryFlushDirtyNodes.func1(0x1fcf9, 0xc455580400?)
08:44:28  	/tmp/workspace/Carmen/Race-Detection/carmen/go/database/mpt/node_flusher.go:79 +0x45
08:44:28  github.com/Fantom-foundation/Carmen/go/database/mpt.(*nodeCache).ForEach(0xc3bd97b340, 0xc1363fc8a0)
08:44:28  	/tmp/workspace/Carmen/Race-Detection/carmen/go/database/mpt/node_cache.go:295 +0x99
08:44:28  github.com/Fantom-foundation/Carmen/go/database/mpt.tryFlushDirtyNodes({0xb329d0, 0xc3bd97b340}, {0xb2faa0, 0xc3e5372000})
08:44:28  	/tmp/workspace/Carmen/Race-Detection/carmen/go/database/mpt/node_flusher.go:78 +0x15c
08:44:28  github.com/Fantom-foundation/Carmen/go/database/mpt.startNodeFlusher.func1()
08:44:28  	/tmp/workspace/Carmen/Race-Detection/carmen/go/database/mpt/node_flusher.go:56 +0x208
08:44:28  created by github.com/Fantom-foundation/Carmen/go/database/mpt.startNodeFlusher in goroutine 16253
08:44:28  	/tmp/workspace/Carmen/Race-Detection/carmen/go/database/mpt/node_flusher.go:47 +0x2e5
08:44:28  FAIL	github.com/Fantom-foundation/Carmen/go/database/mpt	265.242s
```

**Comment by kjezek** [comment]
It seems fixed, but I could not find a PR explicitly fixing this
